### ISSUE TITLE
Raw Points

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#12]
I am working on a card that is worth points based on other players' point at the end of the game. Obviously, timing is important on this. Could we come up with some sort of terminology for points scored during the game, as opposed to points printed on cards that are only evaluated at game end (or deckbuilding points)? I am not sure "Raw Points" is the best term, but that is along the lines of what I am thinking.

**Comment by millerj-tc** [comment]
You could refer to "point tokens" potentially? "Token points" vs "Deck points"

**Comment by ACG8** [comment]
Good idea, I'll do that.

**Comment by millerj-tc** [comment]
One problem with end of game point modifiers is that it could make it impossible to win. Imagine a deck with -4 EOG points. They have 19 points and their opponent has 17. It's impossible for them to win and they are discouraged from ending the game. Or a deck with +7 EOG points vs a deck with 0 EOG points. As soon as the +7 deck gets to 14, the 0 EOG deck can't win.

We could make it so that you finish the turn after someone hits 20 to give people time to go over the cap? It's still awkward though.
