### ISSUE TITLE
Need shorter term for "top card of a player's mind"

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#14]
Many effects reference the top card of a player's mind; we need a shorter word for this. Related to #11.

**Comment by millerj-tc** [comment]
I'm a little worried about terminology creep at this point. But it is also a phrase we're using a lot. Testing with "crest" as a synonym:

> Reveal the top card of another player's mind.

vs

> Reveal another player's crest.

Saves 15 characters. 16 if you can come up with a four letter word, or less if the synonym ends up being longer. That is a lot of characters but the lexicon is starting to feel crowded. 

To contrast, "bury" and "precise dive" (if we decide to go with that) are good examples of Lucid terminology because those actions don't take place in other games and are complicated (bury refers to a thing  -- the card, an action -- move it from its current location, and a final position -- the bottom of the deck. Dive is even more complicated.) Other games refer to the top of a deck however, and special terminology would just compacts two things -- the card and the position.

But like  I said we do reference it A LOT so it still may be worth it.

**Comment by ACG8** [comment]
What about just "Top card". Not "Top card of X player's mind", but just "Top card"?

So:

> Reveal another player's top card

We could extend this to referencing any card according to its position relative to the top of the stack: "second card", "third card", "bottom card", "nth card", etc.

This seems a bit more intuitive than crest, but is shorter than putting the full specification.

After all, it isn't as though anything else a player has possesses a "top card".

**Comment by millerj-tc** [comment]
Yeah, that's a really good solution. I'll implement that across my sets.
