### ISSUE TITLE
Ownership of Effects

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#15]
Does it matter who a card specifies as the actor in verbs such as "bury"?

For example, contrast the following two cards:

`Trap: Bury the top card of the diver's mind`
`Trap: The diver buries the top card of their mind`

Do we want these to be mechanically different or not? This is relevant to a comment I made on #6 regarding **Argh Matey**.

**Comment by millerj-tc** [comment]
In Magic ownership of effects is important, so my instinct is to label things that way. It can be a helpful balancing tool and expand design space by limiting powerful effects so that only effects another player controls can trigger them (you have less control over it, so the power level can be pushed.)

I'm not convinced we need it, but that's my reasoning.
