### ISSUE TITLE
Have You Seen My Friend? (Lucid)

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#181]
![image](https://user-images.githubusercontent.com/3642851/43497293-0b66252e-9507-11e8-83e3-d68e399b6cb2.png)

**Comment by ANRTheBigBoy** [comment]
This is very easy to trigger. I like the archetype of big hand rush, but I worry this is a little too good and hard to interact with. Maybe make it "another player's middle card". That way people can interact by hitting each other's middle cards, but then they are staying away from your stuff so that helps you too. Just a small nerf to a strong card.

**Comment by millerj-tc** [comment]
Oh a flavor-based argument. Sold lol.
