### ISSUE TITLE
New Rippo

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#196]
![image](https://user-images.githubusercontent.com/3642851/43719165-9104a09e-9952-11e8-8f02-8a6fea545a6a.png)

Hard to evaluate how bad it is to prepare 3 cards at random. We can cut this card completely, just wanted to take a swing at it.

**Comment by millerj-tc** [comment]
So you would exchange completely random prepared cards for .83 of a dream?

**Comment by ANRTheBigBoy** [comment]
In a handless deck or in the first few turns, ya. Make it 2 if you think it's bad. 3 is a lot tho.

**Comment by ACG8** [comment]
I agree. 1 is plenty. Should be compared to Shelter from the Dark; it is better in many ways even at [i1] because it doesn't use up one of the three slots. The fact that your prepared cards are now random is perhaps enough of a downside to obfuscate which is better, but even at [i2] it would be way too good (especially in a handless deck where you expect your cards to all be basically random anyway).

**Comment by ACG8** [comment]
Plus it combos really well with other prep-phase lucids. Honestly, I could even see an argument for not giving an insight bonus at all, though that would go against the policy of ensuring that combo cards such as The Cleanser have an upside independent of the rest of the cards in your mind.

**Comment by millerj-tc** [comment]
Ok, I'll print it at i1 and we can see how that goes.

I'll go ahead and move it now.
