### ISSUE TITLE
Making barriers and traps more multiplayer-friendly

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#20]
Barriers and traps are intrinsically a little weird give that this is a natively multiplayer game. This is a discussion about design principles about how to make barriers and traps fun and interesting.

**Comment by millerj-tc** [comment]
How would you feel about changing **Nevaeh, Petrified Faerie** in the Elites starter to:

> Barrier (6): Cancel the dive. Each player loses 3 points.

I was thinking the "mutually beneficial" is good for multiplayer, but what if it's just all around bad for everyone? That way the diver isn't uniquely punished.

I think that's the main thing we want to avoid. That feeling like diving other minds is bad because you get uniquely punished for it -- since that was a big complaint about accessing barriers. The playtesters didn't like that they felt like they had no good option of what to do with it -- simply by accessing it they helped everyone more than they helped themselves.

**Comment by ACG8** [comment]
Re: Proposed change for Nevaeh:

So the owner would be paying 6 credits to cancel the dive and reduce everybody's score by 3? It still hurts the diver and divee more than other players, but it could work. Especially if the player that controls Nevaeh is losing and wants to stall the game; although 6 resources seems like a pretty steep cost.

I think making it so that bad effects either affect everybody or affect somebody other than the diver (e.g. **The Winter That Walks**) is probably a good way to go. Let's go over the existing cards and try to modify them with this in mind. I think the therapists already mostly adhere to this, but I can take a look at the Libertines (since they are assigned to me anyway).

**Comment by ACG8** [comment]
For the therapists, the current approach of traps/barriers that mostly help the owner already works; for other factions, perhaps another approach is building a benefit (even a small one) into the trap. For example, with **Disappointing Ice Cream**, which currently reads:

> Trap: The diver loses 1 resource and 1 point.

You could reformulate it like this:

> Trap: The diver loses 1 resource and 1 point and may bury their top card.

It's still bad, but it gives them a choice that may be useful in some circumstances.

**Comment by millerj-tc** [comment]
I think another frustrating thing about barriers is that they are unavoidable if you're going to the secret. It means there's no way around them if your opponent maintains enough resources to activate them and that also feels bad. Like if a barrier gives a player on 17 +3 points and you can't avoid it -- that's pretty annoying. Maybe we should just cut barriers and tone down how many points secrets are worth?

**Comment by ACG8** [comment]
I like the barrier mechanic; maybe make more ways to avoid barriers? What if you can always bury a card from your hand to avoid any barrier, for example?

Or perhaps a barrier variant could be made that is optional but available to both players? (Like channel, but activated while passing through)?

I did come up with a more interesting secret ability for the therapists: instead of just giving each player 2 points, it changes the rules after it is exposed so that phantasms no longer reduce points when encountered. Obviously, this benefits Doc Lock disproportionately, but it also helps everybody in a more interesting way than just giving points.

**Comment by ACG8** [comment]
Of course, each secret can only be exposed once, so you are guaranteed to hit all the barriers in your mind only once if somebody dives your secret. And it isn't required that players dive the secret to win.

**Comment by millerj-tc** [comment]
So the mechanic would be a beneficial effect that any player gets who
plunges through?

I think that's fine. We can find other ways to help elites protect their
secrets.
