### ISSUE TITLE
Paradise from Ruin

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#240]
Too much turn 1 variance

**Comment by ANRTheBigBoy** [comment]
How about a dream that reveals cards off your deck until you reveal a lucid and then activates it? Situationally could serve as a trap, makes deck-building really interesting, gives you an opportunity to build more directly towards a few lucids.

**Comment by ACG8** [comment]
First, "bury this card" is unnecessary.

Second, I think "can't reveal a lucid" is not well defined enough, especially since you are burying the cards as you reveal them (so that there is not clear point at which you stop revealing them). Burying the cards should happen only after the lucid is found, so it is possible for your mind to be completely emptied.

![sailing to consciousness](https://user-images.githubusercontent.com/10094820/44632824-331b4f00-a947-11e8-8066-c4ed57951658.jpg)

**Comment by ACG8** [comment]
This design also serves as a subtle trap to others; if they find it, they might find the lucid they wanted to stay in play replaced.

**Comment by millerj-tc** [comment]
Yeah this wording is clearer

**Comment by ANRTheBigBoy** [comment]
Ya I like that if someone else accesses this it can either be a sick trap or really good for them, but which it is depends on the boardstate and not on their deck.
