### ISSUE TITLE
Change base insight values for cards

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#274]
Does it still make sense?

I was thinking about switching dives to i3 interp bonus with the reverse spot and making lucids i2.

It made me think about why we have the differential at all, but I don't have time to fully think it through right now so I'm leaving a note to myself.

**Comment by ANRTheBigBoy** [comment]
I think right now the balance between which card types to put down is really good. I worry if you did this change it will become better to skip on your dive and just play 2-1 of the other types. 

I think lucids (and some dives) that trigger off interpreting dives fit well into the current paradigm.

**Comment by ACG8** [comment]
I think it is good where it is. It already feels slightly bad to hit a lucid (because it benefits the owner), but not so much as to lead to a Negative Play Experience. This would just make hitting a Lucid feel terrible.

**Comment by ACG8** [comment]
Oh I see, dives would have the reverse spot

**Comment by ACG8** [comment]
I still don't feel like this change is really needed. The card types feel fine as they are.

As far as why there is a differential, here are my thoughts.

If all cards were worth the same points, then hitting anything but a dream feels terrible. As it is, hitting a non-dream has a small consolation prize in the form of more points (yes, dreams might have more points anyway, but they might also just have a different resource and no points).

As long as non-dream cards are worth different amounts than a dream anyway, having a differential between dives and lucids costs nothing extra in terms of complexity and makes the game more interesting by creating more of a distinction between the other two card types. Hitting a dive is often (though not always) more disruptive than hitting a lucid due to the reverse spot bonus, so it makes sense for them to be worth fewer points.

**Comment by millerj-tc** [comment]
The thing I don't like about it is that hitting a dive never feels good. It's a lose-lose situation unless you're trying to ruin one specific player's day. People don't like their dive being taken and you don't like taking it. Maybe lucids and dives should be worth i3? That way at least one person is having a good experience?
