### ISSUE TITLE
Bruhn, Forst Shaman, etc.

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#279]
The only time the tester on Saturday seemed very disinterested (took out his phone during a game) was during a Bruhn resolution.

We already have plenty of handsize hate, it doesn't seem like hand interpretation is bringing anything essential to the table to check that archetype.

I'd be fine with cutting all hand interpret effects or switching them all to random.

**Comment by ACG8** [comment]
Don't make them random. The only reason hand interpretation is viable is because of the sheer choice it gives you against high-draw decks. Make it random and nobody will use it.

I don't think hand access should be designed as a "hate" card; it is advantageous in a high-draw environment, but doesn't (and shouldn't) really hurt the high-hand players. To make it more appealing, I would say tack on card disruption effects. So you interpret a card from a hand, they draw a card, and you bury a prepared card.

In general, I don't think "bury a prepared card" is something that should have a cost, because it doesn't benefit the player who does it exclusively (it benefits everybody but the target). So top card/hand access should always have free burial to avoid the issue of it indirectly benefiting whoever goes after the player who accesses top.

If top/hand access always buries a card, I think it will become more interesting. I really like hand access, but am hesitant to use it because it is so beneficial to the player you would otherwise have deprived of a card.

**Comment by millerj-tc** [comment]
What do you think about this, @ANRTheBigBoy?

I'm inclined to remove hand interpret because of resolution time.

As far as free prepared card buries on top card interprets, I'm leaving that as a development question.

**Comment by ANRTheBigBoy** [comment]
Get hand access out. It's really annoying.

As far as the prepared card burying. I like when it's tied to a threshold (or tapping will, which is sort of like a threshold). Having to actually expend something (burying cards from hand) for disruption is weird because if the issue Ananda points out. 

We can tie the burying effect on top card dives to:
tapping will
having X points
having X cards in hand
having 2 or fewer cards in hand

Also the fate of top-card stuff depends a little on what we do with reverse spot, since if someone sets up dive-lucid-lucid (which I do a lot, especially if I have late-game dreams), you actually get them kinda good if you do a top card dive instead of taking one of their lucids.

**Comment by ACG8** [comment]
Even having a threshold doesn't really make sense; it doesn't uniquely benefit the user. I would just make the burying baseline for all top/bottom card interprets, and place thresholds on the actual benefits to the player.

**Comment by ANRTheBigBoy** [comment]
Access top card then bury a prepared card isn't really different than just "interpret a prepared card". You lose the spot bonus, but the card effect replaces that with some bonus. 

I would rather delete top card access from the game entirely than having it just always bury a prepared card. 

That said, I think we need to play with the top card access cards a lot more before making this decision. Maybe even tracking the value of the undisrupted card to the other players over the course of a game. 

In a 3 player game, denying 1 pt from another player is worth roughly 1/2 point to the player doing the denial (because you could alternate the player that you disrupt). It's actually worth even more because near the end of the game you can target intelligently. It should not be 0 cost 0 requirement.
