### ISSUE TITLE
Make Therapist starter deck

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#3]
Basic faction concept: Abilities that benefit other players and yourself and also focus on getting to other players' secrets.

**Comment by millerj-tc** [comment]
I think getting other players' secrets should definitely feel like a secondary theme. For flavor reasons: therapy shouldn't have to uncover your deepest darkest stuff to be helpful, and also that solidifies the thieves as the people most concerned about going all the way to the bottom.

Some therapist IDs/cards might care more about secrets, but generally I think their primary focus should be mutually beneficial effects.

**Comment by ACG8** [comment]
I agree. I am focusing on the mutually beneficial effects for the starter deck. Lisa Lockburn is all about uncovering phantasms and "helping" players to "work through them".

**Comment by millerj-tc** [comment]
Reminder: "Beyond the Herd" should read: "_Channel:_Each player gains 1 resource and you gain 1 resource."

**Comment by millerj-tc** [comment]
Some cards are currently formatted: "[Ability]: The diver..." and some are formatted "[Ability]: Diver..."

I think I like the first one better because it sounds nicer when you read it, but the second one is more space efficient. What do you think?

**Comment by ACG8** [comment]
I prefer space efficiency myself. As effects get longer, having conventions that save space will be important.

**Comment by millerj-tc** [comment]
I really like the name **The Winter That Walks** and the flavor of **Memory Trader**.

**Comment by millerj-tc** [comment]
Also I pushed a commit but didn't label it correctly so it didn't show up here: I changed the wording of **Fields of Sweet**. "Diver may access any reverie passed during this plunge" -> "If the diver plunged, they may access any other reverie they revealed."

**Comment by millerj-tc** [comment]
I'm not going to change any of these cards yet, but here are some notes:

I really like  the idea behind **Respite**, but I don't like cards that don't stay in play but have an ongoing effect. We could introduce a permanent type and a condition for burying,  we could make it a face up on top of the mind card,  or (simplest solution) make it a Lucid card that reads something like 

> "Lucid:  Before another player dives, you may bury this card. If you do, each time they would lose points, you gain that many points instead."

 The card is still buried, but at least it only affects a very specific game action that is right about to happen.

I'm a little hesitant about **Winter** for the same reason. This is way grosser, but we could template it like this: 

> "As long as this card is face up on top of your mind, when a card is accessed, it gains the phantasm type. Then, bury this card.
> Trap: Turn this card face up and place it on top of its mind."

 We could still do it your way, I'm just exploring alternatives. Maybe we do need some kind of permanent type?

**Worth Protecting** -- I think the "before" terminology works here (as long as the comprehensive rules stipulate that "before" and "after" always mean "immediately before" or "immediately after" like Destiny). 

> "Lucid: Before another player accesses a phantasm, you may access it instead. If you do, that player gains 1 point."

**Facade** -- Cool card, the flavor is dope! Since we already have "reveal" as a term, I think I've used "look" on other cards to indicate private information (Like **Mind Bind** in the Libertines deck.) So this card could read: 

> "Barrier: The diver looks at the card beneath this one in your mind. Look at the top card of the diver's mind."


In general I'm a little worried that the therapist barriers are a bit underpowered, especially since the therapist secret is worth a lot of points. Maybe it could be:

> Expose: Gain 8 points. Owner gains 2 points.

Deck points -4?

**Comment by ACG8** [comment]
> I really like the idea behind Respite, but I don't like cards that don't stay in play but have an ongoing effect.

Fair enough. I have reworked it a little; it now does not give you points directly for preventing point loss, but is more powerful for Lockburn (since she wants to find other players' phantasms):

```
If this card is face up on top of your mind, no player can lose points.
Trap: You may turn this card face up and put it on top of your mind.
(Does not affect points that are spent)
```

**Comment by ACG8** [comment]
> I'm a little hesitant about Winter for the same reason.

I'm less concerned with this one. With Winter, you only need to remember it for the next dive, which will happen immediately after the current one. Your way would certainly work, though.

**Comment by millerj-tc** [comment]
Let's keep **Winter** the same for now.

**Comment by millerj-tc** [comment]
Sorry, one more question about **Winter**. Is the intent for this to carry over between turn? Otherwise it should specify "this turn."

**Comment by millerj-tc** [comment]
Closing all "starter deck" issues. Further changes to faction duel decks can be dealt with through either specific issues or general new version issues (0.06)
