### ISSUE TITLE
Path of Peace

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#388]
![](https://user-images.githubusercontent.com/3642851/55929875-6237b580-5be4-11e9-849b-8094116581f8.png)

**Comment by ACG8** [comment]
First ability is fiddly (tutoring and shuffling every turn); we can try it though and see how it feels.

**Comment by ANRTheBigBoy** [comment]
That 2nd ability is really awkward. I'd rather it be 1 of each than 3 of the same. I get that you're supposed to set it up with the first ability, but the problem is you are somewhat likely to not have a dive to play the next turn after using this, which is going to make the resolution effect feel lackluster.

**Comment by ANRTheBigBoy** [comment]
And I agree that the shuffling is fiddly...

**Comment by millerj-tc** [comment]
![image](https://user-images.githubusercontent.com/3642851/56011645-38e35c00-5cae-11e9-9153-983a71afd1ec.png)

**Comment by ANRTheBigBoy** [comment]
Looks good.
