### ISSUE TITLE
Zane, the Prescient

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#391]
![](https://user-images.githubusercontent.com/3642851/55930131-91025b80-5be5-11e9-9a82-ac9937b4b021.png)

**Comment by ACG8** [comment]
I like it, I wonder if the second ability should give more points, though - there may not be an opportunity cost to having a dive prepared (because of the first ability), but there is one to taking up the resolution ability. On the other hand, the first ability is quite good.

**Comment by ACG8** [comment]
Also, I like the art but not so much the name; we can figure out theme later though.

**Comment by ANRTheBigBoy** [comment]
I'd rather make the 2nd ability a little more flexible: 

Bury a prepared card to gain i3

This lets you bury a dive, but also another card. I think this makes the card more fun overall and not too strong. The first ability is well-costed (possibly over-costed by 1, but it's high-potential so that's ok to test as is).

**Comment by ACG8** [comment]
Proposed change "bury to gain i3" was implemented
