### ISSUE TITLE
Mass Import of Text Files into MSE

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#40]
Shared a Google Drive folder with you, if you don't want to do it I can take a crack at it as well.

**Comment by millerj-tc** [comment]
How do you include the card type (phantasm, reverie, symbol) as opposed to ability type (channel/trap/lucid)?

**Comment by ACG8** [comment]
Nice catch. That field (which I am calling the "subtype" of the card, in contrast to the "type") was not being saved properly, due to an unexpected issue with the script I was using to make it easy to populate it. For now, we will just have to write the contents out by hand. I have updated the example to demonstrate the use of the subtype field.
