### ISSUE TITLE
Make Libertine starter deck

### ISSUE THREAD

**Issue by ACG8** [ACG8/Lucid#6]
Basic faction concept: faction that doesn't care about plunging, wants to interact with as many other faction' cards as possible. Good at hand/deck disruption, get victory points from it.

**Comment by ACG8** [comment]
Global Pop Stars Mashup has awkward wording (a bit of a run-on sentence). Proposed revision:
>_Lucid_: After a player gains points, you may bury this to gain 2 points. If you do, that player buries a card from their hand and puts the top card of their mind in their hand.

**Comment by ACG8** [comment]
Actually, an even better wording using the draw keyword:
>_Lucid_: After a player gains points, you may bury this to gain 2 points. If you do, that player buries a card from their hand and draws the top card of their mind.
Could be made even simpler by solving #14 .

**Comment by ACG8** [comment]
Currently, **Argh Matey!** does not trigger off of any cards in the set, at least based on my reading of the ability:

> Lucid: After you bury another player’s reverie, you may gain 1 point

All of the cards in the set that let you bury reveries specify that it is the diver who is burying the reverie, not you.

This leads to an interesting question of how to specify ownership of effects (or whether we should), but I'll open another thread for that.

However, contrast this with **Lil' Goat Wizard** (a.k.a Tauriel), which words a similar effect as:

> Lucid: After one of your cards causes another player to bury a card from their hand, gain 2 points.

**Comment by ACG8** [comment]
Thinking a little bit more about this, it occurs to me that the intent might be that it triggers off of burying reveries after channeling them. Is this the intent? I notice that the rulebook does not say that channeling causes a reverie to be buried, it just says to put the card on the bottom of the mind after using the channel effect.

**Comment by millerj-tc** [comment]
Yeah the intent of the card is that opting to bury as part of the access or channeling will trigger Argh Matey! This also raises the question: Is putting a card on the bottom of your deck during the prep phase "burying" it? My intuition says "yes," but the rules don't read that way and editing them to read that way is awkward since there isn't a parallel term for putting a card on top.

The rulebook would have to read something like:

> You may then bury or put as many cards face down on the top of your mind as you wish, in any order.

Which is super awkward sounding.

So I could reword the card to to trigger like this: 

> Lucid: After you put another player’s reverie on the bottom of their deck, you may gain 1 point

Which seems to cover burying under its umbrella.

Or we could add an addendum to the rules that says something like:

> Whenever a card is put on the bottom of its mind, it is considered "buried"
