### ISSUE TITLE
Design Discussion

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#89]
- Limit number of Lucids with a highly specific trigger associated with an effect that can only happen due to playing a specific card or subset of cards

- A handful (5-10) "level up" effects: where you can spend will to do a better version of the "basic" effect

- More ways to spend will on multiple cards in the same turn

- Keyworded "last player" effect -- a bonus for when you are going last ("Patience")

- Disruption "spot pie":
 -- Outer cards are returned to hand
 --Middle cards are revealed
 -- Inner cards are buried

**Comment by ACG8** [comment]
It occurred to me that we haven't been designing many "prepare" mechanics. I've made a few cards to show how this could be done. One nice thing about effects that let you prepare cards is that they are better the later you are in the turn order, so it helps with the last player problem. They also synergize extremely well with princess cards.

Also, I think that in the same way "draw a card" means from your mind, "prepare a card" should mean from your hand (unless otherwise specified. Similarly, "bury a card" could be assumed to mean from your hand by default.

**Comment by ACG8** [comment]
(I put the cards in a separate file because it looks like you are working on the other slush file right now. We can combine them later).
