### ISSUE TITLE
Tweak Gevurah's Pact

### ISSUE THREAD

**Issue by millerj-tc** [ACG8/Lucid#94]
Make compliant with disruption spot pie

**Comment by millerj-tc** [comment]
![gevurahs pact 1](https://user-images.githubusercontent.com/3642851/42283960-a7202d54-7f70-11e8-9ef7-edb5641285db.jpg)
![gevurahs pact 2](https://user-images.githubusercontent.com/3642851/42283961-a83217fc-7f70-11e8-8e6e-6c94e87aa6e0.jpg)

**Comment by ACG8** [comment]
The lucid version is dangerous, because it could occur during a dive chain (which makes the stack harder to keep track of). I think the dive version is fine, though I might reduce the number of cards revealed to four or three (five seems really good - you are pretty much guaranteed to find something good, even without the second part)
